default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: golangci-lint
        name: Run golangci-lint
        language: docker_image
        pass_filenames: false
        stages: [ pre-commit ]
        entry: -w /src -e GOLANGCI_LINT_CACHE=/src/.cache/golangci-lint -e GOCACHE=/src/.cache/go-build golangci/golangci-lint:v1.64.5 golangci-lint run -v
      - id: commitlint-docker
        name: check commit message for conventional commits
        language: docker_image
        entry: -w /src commitlint/commitlint --edit
        stages: [ commit-msg ]
