name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies
        run: go mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
